# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('keywords', models.TextField()),
                ('security_breach', models.NullBooleanField()),
            ],
        ),
    ]
