# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('date_accessed', models.DateField(auto_now_add=True)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('nlp_keywords', models.TextField()),
                ('cyber_security_occurences', models.PositiveSmallIntegerField(default=0)),
                ('hack_occurences', models.PositiveSmallIntegerField(default=0)),
                ('ip_occurences', models.PositiveSmallIntegerField(default=0)),
                ('breach_occurences', models.PositiveSmallIntegerField(default=0)),
                ('security_breach', models.NullBooleanField()),
            ],
        ),
    ]
