# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_learning', '0002_auto_20161013_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='security_breach',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
