# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_learning', '0003_auto_20161019_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='breach_occurences',
        ),
        migrations.RemoveField(
            model_name='article',
            name='cyber_security_occurences',
        ),
        migrations.RemoveField(
            model_name='article',
            name='hack_occurences',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ip_occurences',
        ),
        migrations.RemoveField(
            model_name='article',
            name='nlp_keywords',
        ),
        migrations.RemoveField(
            model_name='article',
            name='security_breach',
        ),
        migrations.AlterField(
            model_name='article',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_learning.SearchQuery'),
        ),
        migrations.AddField(
            model_name='article',
            name='class_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='active_learning.Label'),
        ),
    ]
