# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_learning', '0004_auto_20161031_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
